[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python -m pip install -r algorithm/requirements.txt"]

[start]
cmd = "cd algorithm && python -m gunicorn realtime_detector:app --bind 0.0.0.0:$PORT"